# Generated by Django 3.1.7 on 2021-03-07 14:18

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country name')),
                ('flag_img', models.ImageField(default='unknown.png', upload_to='flag_img/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('img', models.ImageField(default='unknown.png', upload_to='product_img/', verbose_name='Image')),
                ('consistency', models.TextField(verbose_name='Consistency')),
                ('effect_type', multiselectfield.db.fields.MultiSelectField(choices=[('calming', 'Calming'), ('anti wrinkle', 'Anti wrinkle'), ('skin elasticity', 'Skin elasticity'), ('moisturizing', 'Moisturizing'), ('skin microbiome', 'Skin microbiome'), ('sun protection', 'Sun protection'), ('lifting', 'Lifting'), ('healing', 'Healing'), ('antipigmentation', 'Antipigmentation')], max_length=113, verbose_name='Effect type')),
                ('skin_type', multiselectfield.db.fields.MultiSelectField(choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('dehydrated', 'Dehydrated'), ('aging', 'Aging'), ('teenage', 'Teenage'), ('baby', 'Baby'), ('problem', 'Problem'), ('combination', 'Combination'), ('all', 'All')], max_length=69, verbose_name='Skin type')),
                ('for_what', multiselectfield.db.fields.MultiSelectField(choices=[('face', 'Face'), ('eyes', 'Eyes'), ('neck', 'Neck'), ('body', 'Body'), ('hair', 'Hair')], max_length=24, verbose_name='For what')),
                ('ebay_link', models.CharField(max_length=3000, verbose_name='Ebay(link)')),
                ('blog_link', models.CharField(max_length=3000, verbose_name='Blog(link)')),
                ('youtube_link', models.CharField(max_length=3000, verbose_name='Youtube(link)')),
                ('brend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brend', to='app.brend', verbose_name='Brend')),
            ],
        ),
        migrations.AddField(
            model_name='brend',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brend_country', to='app.country', verbose_name='Country'),
        ),
    ]
