# Generated by Django 3.1.7 on 2021-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brend',
            new_name='brend_name',
        ),
        migrations.AddField(
            model_name='product',
            name='consistency_img',
            field=models.ImageField(default='unknown.png', upload_to='product_img/consistency/', verbose_name='Consistency image'),
        ),
    ]
