# Generated by Django 3.1.7 on 2021-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210406_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ph',
            field=models.CharField(blank=True, choices=[(None, 'Absent'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3, null=True, verbose_name='ph'),
        ),
    ]
