# Generated by Django 3.1.7 on 2021-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210330_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_img',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/consistency/', verbose_name='Ingredients image'),
        ),
    ]
