# Generated by Django 3.1.7 on 2021-04-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210413_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='amazon(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='facebook(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='instagram(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='telegram(link)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
