# Generated by Django 3.1.7 on 2021-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210514_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients_list',
            field=models.ManyToManyField(blank=True, null=True, to='app.Ingredient'),
        ),
    ]
