# Generated by Django 3.1.7 on 2021-03-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210330_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_img',
        ),
        migrations.AddField(
            model_name='country',
            name='flag_img_name',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Flag image name'),
        ),
    ]
