# Generated by Django 3.1.7 on 2021-04-26 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210426_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 13, 0, 24, 505896), verbose_name='date'),
        ),
    ]
