# Generated by Django 3.1.7 on 2021-03-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210330_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_img_name',
        ),
    ]
