# Generated by Django 3.1.7 on 2021-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_country_flag_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_img_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flag image name'),
        ),
    ]
