# Generated by Django 3.1.7 on 2021-03-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_country_flag_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='line'),
        ),
    ]
