# Generated by Django 3.1.7 on 2021-05-03 09:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210503_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='unknown.png', upload_to=app.models.get_img_upload_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_img',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_img_upload_path, verbose_name='ingredients image'),
        ),
    ]
