# Generated by Django 3.1.7 on 2021-05-03 10:13

import app.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210503_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link_en',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='amazon(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_link_ru',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='amazon(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_en',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_ru',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='product',
            name='blog_link_en',
            field=models.CharField(blank=True, default='https://beauty-granny.com', max_length=3000, null=True, verbose_name='blog(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='blog_link_ru',
            field=models.CharField(blank=True, default='https://beauty-granny.com', max_length=3000, null=True, verbose_name='blog(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='ebay_link_en',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='ebay(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ebay_link_ru',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='ebay(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='effect_type_en',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('calming', 'Calming'), ('anti wrinkle', 'Anti wrinkle'), ('skin elasticity', 'Skin elasticity'), ('moisturizing', 'Moisturizing'), ('skin microbiome', 'Skin microbiome'), ('sun protection', 'Sun protection'), ('lifting', 'Lifting'), ('healing', 'Healing'), ('antipigmentation', 'Antipigmentation')], max_length=113, null=True, verbose_name='effect type'),
        ),
        migrations.AddField(
            model_name='product',
            name='effect_type_ru',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('calming', 'Calming'), ('anti wrinkle', 'Anti wrinkle'), ('skin elasticity', 'Skin elasticity'), ('moisturizing', 'Moisturizing'), ('skin microbiome', 'Skin microbiome'), ('sun protection', 'Sun protection'), ('lifting', 'Lifting'), ('healing', 'Healing'), ('antipigmentation', 'Antipigmentation')], max_length=113, null=True, verbose_name='effect type'),
        ),
        migrations.AddField(
            model_name='product',
            name='facebook_link_en',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='facebook(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='facebook_link_ru',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='facebook(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_what_en',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('face', 'Face'), ('eyes', 'Eyes'), ('neck', 'Neck'), ('body', 'Body'), ('hair', 'Hair')], max_length=24, null=True, verbose_name='for what'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_what_ru',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('face', 'Face'), ('eyes', 'Eyes'), ('neck', 'Neck'), ('body', 'Body'), ('hair', 'Hair')], max_length=24, null=True, verbose_name='for what'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_en',
            field=models.ImageField(default='unknown.png', null=True, upload_to=app.models.get_img_upload_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_ru',
            field=models.ImageField(default='unknown.png', null=True, upload_to=app.models.get_img_upload_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_en',
            field=models.TextField(null=True, verbose_name='ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_img_en',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_img_upload_path, verbose_name='ingredients image'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_img_ru',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_img_upload_path, verbose_name='ingredients image'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_ru',
            field=models.TextField(null=True, verbose_name='ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_link_en',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='instagram(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_link_ru',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='instagram(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='line_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='line'),
        ),
        migrations.AddField(
            model_name='product',
            name='line_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='line'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='ph_en',
            field=models.CharField(blank=True, choices=[(None, 'Absent'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3, null=True, verbose_name='ph'),
        ),
        migrations.AddField(
            model_name='product',
            name='ph_ru',
            field=models.CharField(blank=True, choices=[(None, 'Absent'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3, null=True, verbose_name='ph'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type_en',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('dehydrated', 'Dehydrated'), ('aging', 'Aging'), ('teenage', 'Teenage'), ('baby', 'Baby'), ('problem', 'Problem'), ('combination', 'Combination'), ('all', 'All')], max_length=69, null=True, verbose_name='skin type'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type_ru',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('dehydrated', 'Dehydrated'), ('aging', 'Aging'), ('teenage', 'Teenage'), ('baby', 'Baby'), ('problem', 'Problem'), ('combination', 'Combination'), ('all', 'All')], max_length=69, null=True, verbose_name='skin type'),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram_link_en',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='telegram(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram_link_ru',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='telegram(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_link_en',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='youtube(link)'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_link_ru',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='youtube(link)'),
        ),
    ]
