# Generated by Django 3.1.7 on 2021-05-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210503_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amazon_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amazon_link_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='approved_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='approved_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='blog_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='blog_link_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ebay_link_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facebook_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facebook_link_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_img_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_img_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instagram_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instagram_link_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='line_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='line_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telegram_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telegram_link_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='youtube_link_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='youtube_link_ru',
        ),
    ]
