# Generated by Django 3.1.7 on 2021-05-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210503_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='effect_type_en',
            new_name='effect_type_en_us',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='for_what_en',
            new_name='for_what_en_us',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ingredients_en',
            new_name='ingredients_en_us',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ph_en',
            new_name='ph_en_us',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='skin_type_en',
            new_name='skin_type_en_us',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_en',
        ),
        migrations.AddField(
            model_name='product',
            name='country_en_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country', verbose_name='country'),
        ),
    ]
