# Generated by Django 3.1.7 on 2021-05-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210503_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='country_en_us',
            new_name='country_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='effect_type_en_us',
            new_name='effect_type_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='for_what_en_us',
            new_name='for_what_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ingredients_en_us',
            new_name='ingredients_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ph_en_us',
            new_name='ph_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='skin_type_en_us',
            new_name='skin_type_en',
        ),
    ]
