# Generated by Django 3.1.7 on 2021-05-05 11:00

import app.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210504_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='effect_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='effect_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_what_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_what_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ph_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ph_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_type_ru',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='одобрено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='брэнд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='effect_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('calming', 'Успокаивающий'), ('anti wrinkle', 'От морщин'), ('skin elasticity', 'Для эластичности кожи'), ('moisturizing', 'Увлажняющий'), ('skin microbiome', 'Для микробиома кожи'), ('sun protection', 'Защита от солнца'), ('lifting', 'Подтяжка лица'), ('healing', 'Залечивающий'), ('antipigmentation', 'Антипигментационный')], max_length=113, null=True, verbose_name='ффект'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('face', 'Лицо'), ('eyes', 'Глаза'), ('neck', 'Шея'), ('body', 'Тело'), ('hair', 'Волосы')], max_length=24, null=True, verbose_name='для чего'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='unknown.png', upload_to=app.models.get_img_upload_path, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(verbose_name='ингредиенты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_img',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_img_upload_path, verbose_name='нгредиенты(фото)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='линия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ph',
            field=models.CharField(blank=True, choices=[(None, 'Отсутствует'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3, null=True, verbose_name='ph'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Нормальная'), ('oily', 'Жирная'), ('dry', 'Сухая'), ('dehydrated', 'Обезвоженная'), ('aging', 'Возрастная'), ('teenage', 'Подростковая'), ('baby', 'Детская'), ('problem', 'Проблемная'), ('combination', 'Комбинированная'), ('all', 'Для все типов')], max_length=69, null=True, verbose_name='тип кожи'),
        ),
    ]
