# Generated by Django 3.1.7 on 2021-05-05 14:37

import app.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210505_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='effect_type_en',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('calming', 'Calming'), ('anti wrinkle', 'Anti wrinkle'), ('skin elasticity', 'Skin elasticity'), ('moisturizing', 'Moisturizing'), ('skin microbiome', 'Skin microbiome'), ('sun protection', 'Sun protection'), ('lifting', 'Lifting'), ('healing', 'Healing'), ('antipigmentation', 'Antipigmentation')], max_length=113, null=True, verbose_name='effect type'),
        ),
        migrations.AddField(
            model_name='product',
            name='effect_type_ru',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('calming', 'Calming'), ('anti wrinkle', 'Anti wrinkle'), ('skin elasticity', 'Skin elasticity'), ('moisturizing', 'Moisturizing'), ('skin microbiome', 'Skin microbiome'), ('sun protection', 'Sun protection'), ('lifting', 'Lifting'), ('healing', 'Healing'), ('antipigmentation', 'Antipigmentation')], max_length=113, null=True, verbose_name='effect type'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_what_en',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('face', 'Face'), ('eyes', 'Eyes'), ('neck', 'Neck'), ('body', 'Body'), ('hair', 'Hair')], max_length=24, null=True, verbose_name='for what'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_what_ru',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('face', 'Face'), ('eyes', 'Eyes'), ('neck', 'Neck'), ('body', 'Body'), ('hair', 'Hair')], max_length=24, null=True, verbose_name='for what'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type_en',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('dehydrated', 'Dehydrated'), ('aging', 'Aging'), ('teenage', 'Teenage'), ('baby', 'Baby'), ('problem', 'Problem'), ('combination', 'Combination'), ('all', 'All')], max_length=69, null=True, verbose_name='skin type'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type_ru',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('dehydrated', 'Dehydrated'), ('aging', 'Aging'), ('teenage', 'Teenage'), ('baby', 'Baby'), ('problem', 'Problem'), ('combination', 'Combination'), ('all', 'All')], max_length=69, null=True, verbose_name='skin type'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='country name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_country', to='app.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='effect_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('calming', 'Calming'), ('anti wrinkle', 'Anti wrinkle'), ('skin elasticity', 'Skin elasticity'), ('moisturizing', 'Moisturizing'), ('skin microbiome', 'Skin microbiome'), ('sun protection', 'Sun protection'), ('lifting', 'Lifting'), ('healing', 'Healing'), ('antipigmentation', 'Antipigmentation')], max_length=113, null=True, verbose_name='effect type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('face', 'Face'), ('eyes', 'Eyes'), ('neck', 'Neck'), ('body', 'Body'), ('hair', 'Hair')], max_length=24, null=True, verbose_name='for what'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='unknown.png', upload_to=app.models.get_img_upload_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_img',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_img_upload_path, verbose_name='ingredients image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ph',
            field=models.CharField(blank=True, choices=[(None, 'Absent'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3, null=True, verbose_name='ph'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('dehydrated', 'Dehydrated'), ('aging', 'Aging'), ('teenage', 'Teenage'), ('baby', 'Baby'), ('problem', 'Problem'), ('combination', 'Combination'), ('all', 'All')], max_length=69, null=True, verbose_name='skin type'),
        ),
    ]
