# Generated by Django 3.1.7 on 2021-05-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210505_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='effect_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='effect_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_what_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_what_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_type_ru',
        ),
    ]
