# Generated by Django 3.1.7 on 2021-05-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210505_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients_img',
        ),
    ]
