# Generated by Django 3.1.7 on 2021-05-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20210527_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
